spring:
  batch:
    verbose: true
    jdbc:
      initialize-schema: never
    job:
      enabled: true
  application:
    name: market-data-service
  jpa:
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enable: true
alphavantage:
  api:
    key: KOCQERY640FBBCKJ
yahoo:
  symbols: "^GSPC"
logging:
  level:
    org.springframework.jdbc.datasource.init: INFO
    org.springframework.batch.core: INFO
server:
  port: 8081