spring:
  batch:
    verbose: true
    jdbc:
      initialize-schema: never
    job:
      enabled: true
  application:
    name: market-data-service
  jpa:
    hibernate:
      ddl-auto: update
  threads:
    virtual:
      enable: true
alphavantage:
  api:
    key: KOCQERY640FBBCKJ
logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.batch.core: DEBUG