server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: user-auth-route
          uri: ${USER_SERVICE_URI:http://user-service:8080}
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: userAuthCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: user-service-route
          uri: ${USER_SERVICE_URI:http://user-service:8080}
          predicates:
            - Path=/api/portfolios/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user
        - id: market-data-route
          uri: ${MARKET_DATA_SERVICE_URI:http://market-data-service:8081}
          predicates:
            - Path=/api/symbols/**,/api/symbol-filters/**,/api/paginatedSymbols/**
          filters:
            - name: CircuitBreaker
              args:
                name: marketDataCircuitBreaker
                fallbackUri: forward:/fallback/market-data

jwt:
  secret: ${JWT_SECRET:YmFja2RhdGVkLXNlY3JldC1rZXktZm9yLW51dmVzdGE=}

management:
  endpoints:
    web:
      exposure:
        include: health,info

resilience4j:
  circuitbreaker:
    instances:
      userAuthCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      userServiceCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      marketDataCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
