server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: user-auth-route
          uri: ${USER_SERVICE_URI:lb://user-service}
          predicates:
            - Path=/api/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: userAuthCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: user-service-route
          uri: ${USER_SERVICE_URI:lb://user-service}
          predicates:
            - Path=/api/portfolios/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user
        - id: market-data-route
          uri: ${MARKET_DATA_SERVICE_URI:lb://market-data-service}
          predicates:
            - Path=/api/symbols,/api/symbols/**,/api/symbol-filters,/api/symbol-filters/**,/api/paginatedSymbols,/api/paginatedSymbols/**,/api/prices,/api/prices/**
          filters:
            - name: CircuitBreaker
              args:
                name: marketDataCircuitBreaker
                fallbackUri: forward:/fallback/market-data

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:YmFja2RhdGVkLXNlY3JldC1rZXktZm9yLW51dmVzdGE=}

management:
  endpoints:
    web:
      exposure:
        include: health,info

gateway:
  cors:
    allowed-origins:
      - http://localhost:5173

resilience4j:
  circuitbreaker:
    instances:
      userAuthCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      userServiceCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      marketDataCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
