spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:nuvesta}
    password: ${SPRING_DATASOURCE_PASSWORD:nuvesta}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  threads:
    virtual:
      enable: true

jwt:
  secret: YmFja2RhdGVkLXNlY3JldC1rZXktZm9yLW51dmVzdGE=
  expiration: 3600000
